"""Deterministic, evidence-grounded, simulated AR cash application."""

from app.cash_application.controls import evaluate_cash_application
from app.cash_application.evaluation import CashApplicationCaseInput, run_case
from app.cash_application.ledger import LedgerInvariantError, SimulatedCashLedger
from app.cash_application.models import (
    AllocationKind,
    ApplicationDecision,
    ApplicationKind,
    ApplicationStatus,
    CashReceipt,
    ControlDisposition,
    EvidenceRef,
    EvidenceSource,
    ExceptionStatus,
    InvoiceApplicationResult,
    InvoiceStatus,
    OpenARItem,
    PolicyReference,
    PolicyStatus,
    ReceiptAllocationStatus,
    ReceiptDirection,
    ReceiptIdentity,
    ReceiptSettlementStatus,
    RemittanceEvidence,
    RemittanceLine,
    ResidualKind,
    ReviewStatus,
    ShortPayPolicy,
    SimulatedPostingResult,
)

__all__ = [
    "AllocationKind",
    "ApplicationDecision",
    "ApplicationKind",
    "ApplicationStatus",
    "CashReceipt",
    "CashApplicationCaseInput",
    "ControlDisposition",
    "EvidenceRef",
    "EvidenceSource",
    "ExceptionStatus",
    "InvoiceApplicationResult",
    "InvoiceStatus",
    "LedgerInvariantError",
    "OpenARItem",
    "PolicyReference",
    "PolicyStatus",
    "ReceiptAllocationStatus",
    "ReceiptDirection",
    "ReceiptIdentity",
    "ReceiptSettlementStatus",
    "RemittanceEvidence",
    "RemittanceLine",
    "ResidualKind",
    "ReviewStatus",
    "ShortPayPolicy",
    "SimulatedCashLedger",
    "SimulatedPostingResult",
    "evaluate_cash_application",
    "run_case",
]
